export const menuData = {
  appetizers: {
    id: 'appetizers',
    items: [
      {
        id: 1,
        name: { ro: 'Bruschette cu roșii', en: 'Tomato Bruschetta', ru: 'Брускетта с томатами' },
        price: 85,
        shortDesc: { ro: 'Pâine prăjită cu roșii proaspete și busuioc', en: 'Toasted bread with fresh tomatoes and basil', ru: 'Поджаренный хлеб со свежими томатами и базиликом' },
        fullDesc: { ro: 'Felii de pâine ciabatta prăjite la perfecție, acoperite cu roșii cherry proaspete, busuioc aromat, usturoi și un strop de ulei de măsline extravirgin. Servite cu parmezan ras.', en: 'Perfectly toasted ciabatta slices topped with fresh cherry tomatoes, aromatic basil, garlic, and a drizzle of extra virgin olive oil. Served with grated Parmesan.', ru: 'Идеально прожаренные ломтики чиабатты с свежими помидорами черри, ароматным базиликом, чесноком и оливковым маслом. Подаётся с тёртым пармезаном.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/0a9062e6f_generated_18dd5c4b.png',
        weight: '220g',
      },
      {
        id: 2,
        name: { ro: 'Hummus clasic', en: 'Classic Hummus', ru: 'Классический хумус' },
        price: 75,
        shortDesc: { ro: 'Cremă de năut cu tahini și pâine', en: 'Chickpea cream with tahini and bread', ru: 'Крем из нута с тахини и хлебом' },
        fullDesc: { ro: 'Hummus cremos preparat din năut fiert, pastă de susan tahini, suc de lămâie proaspăt și usturoi. Servit cu pâine caldă și boia de ardei dulce.', en: 'Creamy hummus made from cooked chickpeas, tahini sesame paste, fresh lemon juice, and garlic. Served with warm bread and sweet paprika.', ru: 'Кремовый хумус из варёного нута, пасты тахини, свежего лимонного сока и чеснока. Подаётся с тёплым хлебом и сладкой паприкой.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/0a9062e6f_generated_18dd5c4b.png',
        weight: '200g',
      },
      {
        id: 3,
        name: { ro: 'Carpaccio de vită', en: 'Beef Carpaccio', ru: 'Карпаччо из говядины' },
        price: 135,
        shortDesc: { ro: 'Felii subțiri de vită cu rucola și parmezan', en: 'Thin beef slices with arugula and Parmesan', ru: 'Тонкие ломтики говядины с руколой и пармезаном' },
        fullDesc: { ro: 'Felii subțiri de mușchi de vită premium, servite cu rucola proaspătă, fulgi de parmezan, capere și sos de lămâie. O delicatesă italiană autentică.', en: 'Thin slices of premium beef tenderloin, served with fresh arugula, Parmesan flakes, capers, and lemon sauce. An authentic Italian delicacy.', ru: 'Тонкие ломтики премиальной говяжьей вырезки с свежей руколой, пармезаном, каперсами и лимонным соусом.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/0a9062e6f_generated_18dd5c4b.png',
        weight: '180g',
      },
    ],
  },
  salads: {
    id: 'salads',
    items: [
      {
        id: 4,
        name: { ro: 'Salată Caesar', en: 'Caesar Salad', ru: 'Салат Цезарь' },
        price: 110,
        shortDesc: { ro: 'Salată verde cu pui, crutoane și parmezan', en: 'Green salad with chicken, croutons and Parmesan', ru: 'Зелёный салат с курицей, крутонами и пармезаном' },
        fullDesc: { ro: 'Salată romană crocantă cu piept de pui la grătar, crutoane crocante din pâine de casă, parmezan și sosul nostru Caesar special. O clasică reinterpretată.', en: 'Crispy romaine lettuce with grilled chicken breast, homemade crunchy croutons, Parmesan, and our special Caesar dressing.', ru: 'Хрустящий салат романо с куриной грудкой на гриле, домашними крутонами, пармезаном и нашим специальным соусом Цезарь.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/4d4e831d5_generated_1090603a.png',
        weight: '300g',
      },
      {
        id: 5,
        name: { ro: 'Salată grecească', en: 'Greek Salad', ru: 'Греческий салат' },
        price: 95,
        shortDesc: { ro: 'Legume proaspete cu brânză feta', en: 'Fresh vegetables with feta cheese', ru: 'Свежие овощи с сыром фета' },
        fullDesc: { ro: 'Roșii, castraveți, ardei, ceapă roșie, măsline Kalamata și brânză feta, toate stropite cu ulei de măsline și oregano proaspăt.', en: 'Tomatoes, cucumbers, peppers, red onion, Kalamata olives, and feta cheese, all drizzled with olive oil and fresh oregano.', ru: 'Помидоры, огурцы, перец, красный лук, оливки Каламата и сыр фета с оливковым маслом и свежим орегано.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/4d4e831d5_generated_1090603a.png',
        weight: '320g',
      },
      {
        id: 6,
        name: { ro: 'Salată cu avocado', en: 'Avocado Salad', ru: 'Салат с авокадо' },
        price: 120,
        shortDesc: { ro: 'Mix de verdețuri cu avocado și semințe', en: 'Green mix with avocado and seeds', ru: 'Микс зелени с авокадо и семенами' },
        fullDesc: { ro: 'Amestec de verdețuri proaspete cu avocado cremos, semințe de dovleac și floarea-soarelui, roșii cherry și vinaigrette de lămâie.', en: 'Fresh greens mix with creamy avocado, pumpkin and sunflower seeds, cherry tomatoes, and lemon vinaigrette.', ru: 'Микс свежей зелени с кремовым авокадо, тыквенными и подсолнечными семечками, томатами черри и лимонным винегретом.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/4d4e831d5_generated_1090603a.png',
        weight: '280g',
      },
    ],
  },
  soups: {
    id: 'soups',
    items: [
      {
        id: 7,
        name: { ro: 'Supă cremă de ciuperci', en: 'Cream of Mushroom Soup', ru: 'Крем-суп из грибов' },
        price: 75,
        shortDesc: { ro: 'Supă cremă cu ciuperci de pădure', en: 'Cream soup with wild mushrooms', ru: 'Крем-суп из лесных грибов' },
        fullDesc: { ro: 'Supă cremă catifelată din ciuperci de pădure, cu smântână proaspătă, crutoane și trufe. Un deliciu cald pentru orice anotimp.', en: 'Velvety cream soup from wild mushrooms with fresh cream, croutons, and truffles. A warm delight for any season.', ru: 'Бархатный крем-суп из лесных грибов со свежими сливками, крутонами и трюфелями.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/1ffead6fe_generated_f5b79648.png',
        weight: '350ml',
      },
      {
        id: 8,
        name: { ro: 'Ciorbă de legume', en: 'Vegetable Soup', ru: 'Овощной суп' },
        price: 65,
        shortDesc: { ro: 'Ciorbă tradițională cu legume proaspete', en: 'Traditional soup with fresh vegetables', ru: 'Традиционный суп со свежими овощами' },
        fullDesc: { ro: 'Ciorbă tradițională moldovenească cu legume de sezon, verdețuri proaspete și smântână. Rețetă de casă, gust de acasă.', en: 'Traditional Moldovan soup with seasonal vegetables, fresh herbs, and sour cream. A homestyle recipe with homestyle taste.', ru: 'Традиционный молдавский суп с сезонными овощами, свежей зеленью и сметаной.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/1ffead6fe_generated_f5b79648.png',
        weight: '400ml',
      },
    ],
  },
  main_courses: {
    id: 'main_courses',
    items: [
      {
        id: 9,
        name: { ro: 'Piept de pui la grătar', en: 'Grilled Chicken Breast', ru: 'Куриная грудка на гриле' },
        price: 155,
        shortDesc: { ro: 'Pui la grătar cu legume coapte', en: 'Grilled chicken with roasted vegetables', ru: 'Курица на гриле с запечёнными овощами' },
        fullDesc: { ro: 'Piept de pui marinat în ierburi mediteraneene, grătat la perfecție și servit cu legume de sezon coapte la cuptor și sos chimichurri.', en: 'Chicken breast marinated in Mediterranean herbs, grilled to perfection, served with oven-roasted seasonal vegetables and chimichurri sauce.', ru: 'Куриная грудка, маринованная в средиземноморских травах, с запечёнными сезонными овощами и соусом чимичурри.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/0dffee353_generated_50a532d6.png',
        weight: '350g',
      },
      {
        id: 10,
        name: { ro: 'Steak de vită', en: 'Beef Steak', ru: 'Стейк из говядины' },
        price: 245,
        shortDesc: { ro: 'Steak premium cu sos de vin roșu', en: 'Premium steak with red wine sauce', ru: 'Премиальный стейк с соусом из красного вина' },
        fullDesc: { ro: 'Mușchi de vită Black Angus gătit la temperatura perfectă, servit cu piure de cartofi trufe și sos de vin roșu redus.', en: 'Black Angus beef tenderloin cooked to perfection, served with truffle mashed potatoes and reduced red wine sauce.', ru: 'Вырезка говядины Блэк Ангус, приготовленная до идеальной температуры, с трюфельным картофельным пюре и соусом из красного вина.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/0dffee353_generated_50a532d6.png',
        weight: '300g',
      },
      {
        id: 11,
        name: { ro: 'Somon la cuptor', en: 'Baked Salmon', ru: 'Запечённый лосось' },
        price: 195,
        shortDesc: { ro: 'Somon cu lămâie și sparanghel', en: 'Salmon with lemon and asparagus', ru: 'Лосось с лимоном и спаржей' },
        fullDesc: { ro: 'File de somon proaspăt copt la cuptor cu lămâie, sparanghel verde și sos de unt cu mărar. Delicat și aromat.', en: 'Fresh salmon fillet baked with lemon, green asparagus, and dill butter sauce. Delicate and aromatic.', ru: 'Свежее филе лосося, запечённое с лимоном, зелёной спаржей и соусом из масла с укропом.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/0dffee353_generated_50a532d6.png',
        weight: '280g',
      },
    ],
  },
  pasta: {
    id: 'pasta',
    items: [
      {
        id: 12,
        name: { ro: 'Carbonara', en: 'Carbonara', ru: 'Карбонара' },
        price: 125,
        shortDesc: { ro: 'Paste cu pancetta, ou și parmezan', en: 'Pasta with pancetta, egg and Parmesan', ru: 'Паста с панчеттой, яйцом и пармезаном' },
        fullDesc: { ro: 'Spaghetti al dente cu sos cremos din gălbenușuri, pecorino romano, pancetta crocantă și piper negru proaspăt măcinat. Rețetă italiană clasică.', en: 'Al dente spaghetti with creamy egg yolk sauce, pecorino romano, crispy pancetta, and freshly ground black pepper. Classic Italian recipe.', ru: 'Спагетти аль денте с кремовым соусом из яичных желтков, пекорино романо, хрустящей панчеттой и свежемолотым перцем.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/87a3cfe8a_generated_3bc2716e.png',
        weight: '350g',
      },
      {
        id: 13,
        name: { ro: 'Penne Arrabiata', en: 'Penne Arrabiata', ru: 'Пенне Арабьята' },
        price: 95,
        shortDesc: { ro: 'Paste cu sos de roșii picant', en: 'Pasta with spicy tomato sauce', ru: 'Паста с острым томатным соусом' },
        fullDesc: { ro: 'Penne rigate cu sos de roșii San Marzano, ardei iute, usturoi și busuioc proaspăt. Picant și satisfăcător.', en: 'Penne rigate with San Marzano tomato sauce, chili peppers, garlic, and fresh basil. Spicy and satisfying.', ru: 'Пенне ригате с соусом из томатов Сан-Марцано, перцем чили, чесноком и свежим базиликом.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/87a3cfe8a_generated_3bc2716e.png',
        weight: '320g',
      },
    ],
  },
  desserts: {
    id: 'desserts',
    items: [
      {
        id: 14,
        name: { ro: 'Tiramisu', en: 'Tiramisu', ru: 'Тирамису' },
        price: 85,
        shortDesc: { ro: 'Desert italian clasic cu mascarpone', en: 'Classic Italian dessert with mascarpone', ru: 'Классический итальянский десерт с маскарпоне' },
        fullDesc: { ro: 'Desert tradițional italian cu straturi de pișcoturi înmuiate în cafea espresso, cremă de mascarpone și cacao naturală. Preparat zilnic.', en: 'Traditional Italian dessert with layers of espresso-soaked ladyfingers, mascarpone cream, and natural cocoa. Made fresh daily.', ru: 'Традиционный итальянский десерт со слоями савоярди, пропитанных эспрессо, кремом маскарпоне и натуральным какао.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/ead44b101_generated_3a202674.png',
        weight: '180g',
      },
      {
        id: 15,
        name: { ro: 'Lava Cake', en: 'Lava Cake', ru: 'Лава Кейк' },
        price: 95,
        shortDesc: { ro: 'Tort de ciocolată cu centru lichid', en: 'Chocolate cake with liquid center', ru: 'Шоколадный торт с жидким центром' },
        fullDesc: { ro: 'Tort de ciocolată neagră premium cu centru lichid fierbinte, servit cu înghețată de vanilie și fructe de pădure proaspete.', en: 'Premium dark chocolate cake with hot liquid center, served with vanilla ice cream and fresh berries.', ru: 'Торт из премиального тёмного шоколада с горячим жидким центром, с ванильным мороженым и свежими ягодами.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/ead44b101_generated_3a202674.png',
        weight: '200g',
      },
    ],
  },
  drinks: {
    id: 'drinks',
    items: [
      {
        id: 16,
        name: { ro: 'Limonadă de casă', en: 'Homemade Lemonade', ru: 'Домашний лимонад' },
        price: 55,
        shortDesc: { ro: 'Limonadă proaspătă cu mentă', en: 'Fresh lemonade with mint', ru: 'Свежий лимонад с мятой' },
        fullDesc: { ro: 'Limonadă proaspătă preparată din lămâi și lime, cu frunze de mentă și sirop de trandafir. Răcoritoare și naturală.', en: 'Fresh lemonade made from lemons and limes, with mint leaves and rose syrup. Refreshing and natural.', ru: 'Свежий лимонад из лимонов и лаймов с листьями мяты и розовым сиропом.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/786fdbaaf_generated_faee843a.png',
        weight: '400ml',
      },
      {
        id: 17,
        name: { ro: 'Smoothie de fructe', en: 'Fruit Smoothie', ru: 'Фруктовый смузи' },
        price: 70,
        shortDesc: { ro: 'Smoothie din fructe de sezon', en: 'Seasonal fruit smoothie', ru: 'Смузи из сезонных фруктов' },
        fullDesc: { ro: 'Smoothie din fructe proaspete de sezon, iaurt grecesc și miere naturală. Un boost de vitamine și energie.', en: 'Fresh seasonal fruit smoothie with Greek yogurt and natural honey. A boost of vitamins and energy.', ru: 'Смузи из свежих сезонных фруктов, греческого йогурта и натурального мёда.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/786fdbaaf_generated_faee843a.png',
        weight: '350ml',
      },
      {
        id: 18,
        name: { ro: 'Cappuccino', en: 'Cappuccino', ru: 'Капучино' },
        price: 45,
        shortDesc: { ro: 'Cafea cu spumă de lapte', en: 'Coffee with milk foam', ru: 'Кофе с молочной пеной' },
        fullDesc: { ro: 'Espresso dublu cu spumă de lapte catifelată și un strop de cacao. Boabe de cafea prăjite special pentru noi.', en: 'Double espresso with velvety milk foam and a dusting of cocoa. Specially roasted coffee beans.', ru: 'Двойной эспрессо с бархатной молочной пеной и какао. Специально обжаренные кофейные зёрна.' },
        image: 'https://media.base44.com/images/public/6a0982e2e3691dc690c8f67d/786fdbaaf_generated_faee843a.png',
        weight: '250ml',
      },
    ],
  },
};