services:
  db:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    build: ./src/backend
    ports:
      - "8000:8000"
    env_file:
      - ./src/backend/.env
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: ./src/frontend
      args:
        VITE_API_URL: /api/v1/
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: