# Generated by Django 6.0.5 on 2026-06-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuproduct',
            name='full_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='menuproduct',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
