# Generated by Django 6.0.5 on 2026-06-12 13:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuproduct_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuproduct',
            name='full_description',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
