# Generated by Django 6.0.5 on 2026-06-16 16:10

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuproduct_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='alt_text_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='alt_text_ro',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='alt_text_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='full_description_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='full_description_ro',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='full_description_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='name_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='short_description_en',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='short_description_ro',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='short_description_ru',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
