# Generated by Django 6.0.5 on 2026-06-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menucategory_name_en_menucategory_name_ro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuproduct',
            name='img_src',
            field=models.ImageField(upload_to='menu/'),
        ),
    ]
