# Generated by Django 6.0.5 on 2026-07-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuproduct_img_src'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menuproduct',
            index=models.Index(fields=['category', 'is_active', 'sort_order'], name='menu_menupr_categor_c907bc_idx'),
        ),
    ]
