# Generated by Django 6.0.5 on 2026-06-11 14:42

import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.page')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='PageHero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_text', models.CharField(max_length=50)),
                ('secondary_text', models.CharField(blank=True, default='', max_length=150)),
                ('img_src', models.ImageField(blank=True, null=True, upload_to='heroes/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='core.page')),
            ],
        ),
        migrations.CreateModel(
            name='ReelsSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagesection')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
            ],
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='TightImageSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagesection')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
            ],
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagesection')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True, default='')),
            ],
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='WideImageSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagesection')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/wide_image/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
            ],
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='ReelItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='core.reelssection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TightImageCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/tight_image/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.tightimagesection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
