# Generated by Django 6.0.5 on 2026-06-09 19:10

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelsSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagesection')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
            ],
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='TightImageSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagesection')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
            ],
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagesection')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True, default='')),
            ],
            bases=('core.pagesection',),
        ),
        migrations.CreateModel(
            name='WideImageSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pagesection')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/wide_image/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
            ],
            bases=('core.pagesection',),
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='section_type',
        ),
        migrations.CreateModel(
            name='ReelItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='core.reelssection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TightImageCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/tight_image/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.tightimagesection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
