# Generated by Django 6.0.5 on 2026-06-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pagehero_main_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tightimagecard',
            old_name='image',
            new_name='img_src',
        ),
        migrations.RenameField(
            model_name='wideimagesection',
            old_name='image',
            new_name='img_src',
        ),
    ]
