# Generated by Django 6.0.5 on 2026-06-16 15:50

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='alt_text_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='alt_text_ro',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='alt_text_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='main_text_en',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='main_text_ro',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='main_text_ru',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='secondary_text_en',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='secondary_text_ro',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='secondary_text_ru',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reelssection',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reelssection',
            name='title_ro',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reelssection',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='alt_text_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='alt_text_ro',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='alt_text_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='full_description_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='full_description_ro',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='full_description_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='short_description_en',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='short_description_ro',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='short_description_ru',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='title_ro',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tightimagecard',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tightimagesection',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tightimagesection',
            name='title_ro',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tightimagesection',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='description_ro',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='title_ro',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='videosection',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='alt_text_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='alt_text_ro',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='alt_text_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='full_description_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='full_description_ro',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='full_description_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='short_description_en',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='short_description_ro',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='short_description_ru',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='title_ro',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wideimagesection',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
