# Generated by Django 6.0.5 on 2026-06-28 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_page_name_en_page_name_ro_page_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('img_src', models.ImageField(upload_to='site/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
