# Generated by Django 6.0.5 on 2026-06-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteimages',
            options={'verbose_name_plural': 'Site images'},
        ),
    ]
