# Generated by Django 6.0.5 on 2026-06-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_siteimages_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteImages',
            new_name='SiteImage',
        ),
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='SiteSetting',
        ),
    ]
