# Generated by Django 6.0.5 on 2026-06-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteimage_created_at_siteimage_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehero',
            name='img_src',
            field=models.ImageField(upload_to='heroes/'),
        ),
    ]
