# Generated by Django 6.0.5 on 2026-07-02 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_pagehero_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tightimagecard',
            name='img_src',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='sections/tight_image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wideimagesection',
            name='img_src',
            field=models.ImageField(default='default', upload_to='sections/wide_image/'),
            preserve_default=False,
        ),
    ]
