# Generated by Django 6.0.5 on 2026-07-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_alter_tightimagecard_img_src_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pagesection',
            index=models.Index(fields=['page', 'is_published', 'sort_order'], name='core_pagese_page_id_a2eae0_idx'),
        ),
        migrations.AddIndex(
            model_name='reelitem',
            index=models.Index(fields=['section', 'sort_order'], name='core_reelit_section_dfb3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='tightimagecard',
            index=models.Index(fields=['section', 'sort_order'], name='core_tighti_section_c0aa40_idx'),
        ),
    ]
